2021-06-25 11:11:09,918 - create_public - ERROR - Error detected
Traceback (most recent call last):
  File "C:\Users\Webdom16\PycharmProjects\TestsCovid\COVID_19_ 9880\Cоздание_исследований\create_public.py", line 31, in genlog
    self.create_public()
  File "C:\Users\Webdom16\PycharmProjects\TestsCovid\COVID_19_ 9880\Cоздание_исследований\create_public.py", line 66, in create_public
    select.select_by_visible_text(u"РђР±С…Р°Р·РёСЏ")
AttributeError: 'NoneType' object has no attribute 'select_by_visible_text'
