2021-06-25 11:38:22,279 - create_public - ERROR - Error detected
Traceback (most recent call last):
  File "C:\Users\Webdom16\PycharmProjects\TestsCovid\COVID_19_ 9880\Cоздание_исследований\create_public.py", line 32, in genlog
    self.create_public()
  File "C:\Users\Webdom16\PycharmProjects\TestsCovid\COVID_19_ 9880\Cоздание_исследований\create_public.py", line 71, in create_public
    driver.find_element_by_xpath("//*[text()=u'РђР±С…Р°Р·РёСЏ']").click()
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
InvalidSelectorException: Message: invalid selector: Unable to locate an element with the xpath expression //*[text()=u'\u0410\u0431\u0445\u0430\u0437\u0438\u044f'] because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//*[text()=u'\u0410\u0431\u0445\u0430\u0437\u0438\u044f']' is not a valid XPath expression.
  (Session info: chrome=91.0.4472.114)

