2021-06-24 16:38:03,773 - __main__ - ERROR - Error detected
Traceback (most recent call last):
  File "C:/Users/Webdom16/Desktop/Питон/COVID_19_ 9880/Cоздание_исследований/create_Antitel.py", line 31, in genlog
    self.create_antitel()
  File "C:/Users/Webdom16/Desktop/Питон/COVID_19_ 9880/Cоздание_исследований/create_Antitel.py", line 180, in create_antitel
    window_after = driver.window_handles[1]
IndexError: list index out of range
