2021-06-24 18:34:10,542 - create_Express - ERROR - Error detected
Traceback (most recent call last):
  File "C:\Users\Webdom16\PycharmProjects\TestsCovid\COVID_19_ 9880\Cоздание_исследований\create_Express.py", line 31, in genlog
    self.create_Express()
  File "C:\Users\Webdom16\PycharmProjects\TestsCovid\COVID_19_ 9880\Cоздание_исследований\create_Express.py", line 180, in create_Express
    window_after = driver.window_handles[1]
IndexError: list index out of range
