2021-06-25 11:45:34,325 - create_public - ERROR - Error detected
Traceback (most recent call last):
  File "C:\Users\Webdom16\PycharmProjects\TestsCovid\COVID_19_ 9880\Cоздание_исследований\create_public.py", line 37, in genlog
    self.create_public()
  File "C:\Users\Webdom16\PycharmProjects\TestsCovid\COVID_19_ 9880\Cоздание_исследований\create_public.py", line 76, in create_public
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH,
AttributeError: 'str' object has no attribute 'element_to_be_clickable'
