2021-06-09 17:30:15,259 - __main__ - ERROR - Error detected
Traceback (most recent call last):
  File "C:\Work\Работа\Питон\COVID_19_ 9880\Cоздание_исследований\create_barcode.py", line 31, in genlog
    self.create_barcode()
  File "C:\Work\Работа\Питон\COVID_19_ 9880\Cоздание_исследований\create_barcode.py", line 54, in create_barcode
    driver.find_element_by_css_selector("span.ui-icon.ui-icon-triangle-1-s").click()
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: chrome not reachable
  (Session info: chrome=90.0.4430.212)

