2021-06-24 17:31:54,339 - create_public - ERROR - Error detected
Traceback (most recent call last):
  File "C:\Users\Webdom16\PycharmProjects\TestsCovid\COVID_19_ 9880\Cоздание_исследований\create_public.py", line 31, in genlog
    self.create_public()
  File "C:\Users\Webdom16\PycharmProjects\TestsCovid\COVID_19_ 9880\Cоздание_исследований\create_public.py", line 47, in create_public
    driver.find_element_by_id("itemForm:tabView:firstName").click()
AttributeError: 'NoneType' object has no attribute 'click'
