2021-06-24 18:32:02,371 - create_Antitel - ERROR - Error detected
Traceback (most recent call last):
  File "C:\Users\Webdom16\PycharmProjects\TestsCovid\COVID_19_ 9880\Cоздание_исследований\create_Antitel.py", line 31, in genlog
    self.create_antitel()
  File "C:\Users\Webdom16\PycharmProjects\TestsCovid\COVID_19_ 9880\Cоздание_исследований\create_Antitel.py", line 180, in create_antitel
    window_after = driver.window_handles[1]
IndexError: list index out of range
